#config_version=5

hardware:
    platform: virtual_pinball

switches:
    s_test00:
        number: 1
    s_test37:
        number: 2
    s_test77_nc:
        number: 3
        type: 'NC'

coils:
    c_test:
        number: 0
    c_test_allow_enable:
        number: 1
        default_hold_power: 1.0
    c_trough_eject:
        number: 2
        default_pulse_ms: 3s

lights:
  test_light:
    number: 3
  test_light2:
    number: 15
    subtype: matrix
  test_gi:
    number: 15
    subtype: gi
